class AcademicPeriodMapping {
  const AcademicPeriodMapping({
    required this.order,
    required this.name,
    required this.sections,
    required this.startTime,
    required this.endTime,
  });

  final int order;
  final String name;
  final List<String> sections;
  final String startTime;
  final String endTime;
}

typedef PeriodDefinition = AcademicPeriodMapping;

class AcademicPeriodMappings {
  const AcademicPeriodMappings._();

  static const all = <AcademicPeriodMapping>[
    PeriodDefinition(
      order: 1,
      name: '上午12节',
      sections: ['第1节', '第2节'],
      startTime: '08:30',
      endTime: '10:10',
    ),
    PeriodDefinition(
      order: 2,
      name: '全天',
      sections: [
        '第1节',
        '第2节',
        '第3节',
        '第4节',
        '中午1节',
        '中午2节',
        '第5节',
        '第6节',
        '第7节',
        '第8节',
        '第9节',
        '第10节',
        '第11节',
        '第12节',
      ],
      startTime: '08:30',
      endTime: '22:30',
    ),
    PeriodDefinition(
      order: 3,
      name: '1-9节',
      sections: [
        '第1节',
        '第2节',
        '第3节',
        '第4节',
        '中午1节',
        '中午2节',
        '第5节',
        '第6节',
        '第7节',
        '第8节',
        '第9节',
      ],
      startTime: '08:30',
      endTime: '19:45',
    ),
    PeriodDefinition(
      order: 4,
      name: '1-8节',
      sections: [
        '第1节',
        '第2节',
        '第3节',
        '第4节',
        '中午1节',
        '中午2节',
        '第5节',
        '第6节',
        '第7节',
        '第8节',
      ],
      startTime: '08:30',
      endTime: '18:10',
    ),
    PeriodDefinition(
      order: 5,
      name: '1-6节',
      sections: ['第1节', '第2节', '第3节', '第4节', '中午1节', '中午2节', '第5节', '第6节'],
      startTime: '08:30',
      endTime: '16:10',
    ),
    PeriodDefinition(
      order: 6,
      name: '第1节',
      sections: ['第1节'],
      startTime: '08:30',
      endTime: '09:15',
    ),
    PeriodDefinition(
      order: 7,
      name: '上午1-4节',
      sections: ['第1节', '第2节', '第3节', '第4节'],
      startTime: '08:30',
      endTime: '12:10',
    ),
    PeriodDefinition(
      order: 8,
      name: '1-7节',
      sections: [
        '第1节',
        '第2节',
        '第3节',
        '第4节',
        '中午1节',
        '中午2节',
        '第5节',
        '第6节',
        '第7节',
      ],
      startTime: '08:30',
      endTime: '17:15',
    ),
    PeriodDefinition(
      order: 9,
      name: '上午123节',
      sections: ['第1节', '第2节', '第3节'],
      startTime: '08:30',
      endTime: '11:15',
    ),
    PeriodDefinition(
      order: 10,
      name: '第2节',
      sections: ['第2节'],
      startTime: '09:25',
      endTime: '10:10',
    ),
    PeriodDefinition(
      order: 11,
      name: '上午234节',
      sections: ['第2节', '第3节', '第4节'],
      startTime: '09:25',
      endTime: '12:10',
    ),
    PeriodDefinition(
      order: 12,
      name: '第3节',
      sections: ['第3节'],
      startTime: '10:30',
      endTime: '11:15',
    ),
    PeriodDefinition(
      order: 13,
      name: '3-11节',
      sections: [
        '第3节',
        '第4节',
        '中午1节',
        '中午2节',
        '第5节',
        '第6节',
        '第7节',
        '第8节',
        '第9节',
        '第10节',
        '第11节',
      ],
      startTime: '10:30',
      endTime: '21:35',
    ),
    PeriodDefinition(
      order: 14,
      name: '上午34节',
      sections: ['第3节', '第4节'],
      startTime: '10:30',
      endTime: '12:10',
    ),
    PeriodDefinition(
      order: 15,
      name: '3-10节',
      sections: [
        '第3节',
        '第4节',
        '中午1节',
        '中午2节',
        '第5节',
        '第6节',
        '第7节',
        '第8节',
        '第9节',
        '第10节',
      ],
      startTime: '10:30',
      endTime: '20:40',
    ),
    PeriodDefinition(
      order: 16,
      name: '3-6节',
      sections: ['第3节', '第4节', '中午1节', '中午2节', '第5节', '第6节'],
      startTime: '10:30',
      endTime: '16:10',
    ),
    PeriodDefinition(
      order: 17,
      name: '3-8节',
      sections: ['第3节', '第4节', '中午1节', '中午2节', '第5节', '第6节', '第7节', '第8节'],
      startTime: '10:30',
      endTime: '18:10',
    ),
    PeriodDefinition(
      order: 18,
      name: '第4节',
      sections: ['第4节'],
      startTime: '11:25',
      endTime: '12:10',
    ),
    PeriodDefinition(
      order: 19,
      name: '中午第1节',
      sections: ['中午1节'],
      startTime: '12:20',
      endTime: '13:15',
    ),
    PeriodDefinition(
      order: 20,
      name: '中午1-2节',
      sections: ['中午1节', '中午2节'],
      startTime: '12:20',
      endTime: '14:20',
    ),
    PeriodDefinition(
      order: 21,
      name: '中午第2节',
      sections: ['中午2节'],
      startTime: '13:25',
      endTime: '14:20',
    ),
    PeriodDefinition(
      order: 22,
      name: '5-12节',
      sections: ['第5节', '第6节', '第7节', '第8节', '第9节', '第10节', '第11节', '第12节'],
      startTime: '14:30',
      endTime: '22:30',
    ),
    PeriodDefinition(
      order: 23,
      name: '下午5-8节',
      sections: ['第5节', '第6节', '第7节', '第8节'],
      startTime: '14:30',
      endTime: '18:10',
    ),
    PeriodDefinition(
      order: 24,
      name: '第5节',
      sections: ['第5节'],
      startTime: '14:30',
      endTime: '15:15',
    ),
    PeriodDefinition(
      order: 25,
      name: '下午56节',
      sections: ['第5节', '第6节'],
      startTime: '14:30',
      endTime: '16:10',
    ),
    PeriodDefinition(
      order: 26,
      name: '下午5-7节',
      sections: ['第5节', '第6节', '第7节'],
      startTime: '14:30',
      endTime: '17:15',
    ),
    PeriodDefinition(
      order: 27,
      name: '5-10节',
      sections: ['第5节', '第6节', '第7节', '第8节', '第9节', '第10节'],
      startTime: '14:30',
      endTime: '20:40',
    ),
    PeriodDefinition(
      order: 28,
      name: '5-11节',
      sections: ['第5节', '第6节', '第7节', '第8节', '第9节', '第10节', '第11节'],
      startTime: '14:30',
      endTime: '21:35',
    ),
    PeriodDefinition(
      order: 29,
      name: '5-9节',
      sections: ['第5节', '第6节', '第7节', '第8节', '第9节'],
      startTime: '14:30',
      endTime: '19:45',
    ),
    PeriodDefinition(
      order: 30,
      name: '第6节',
      sections: ['第6节'],
      startTime: '15:25',
      endTime: '16:10',
    ),
    PeriodDefinition(
      order: 31,
      name: '下午6-8节',
      sections: ['第6节', '第7节', '第8节'],
      startTime: '15:25',
      endTime: '18:10',
    ),
    PeriodDefinition(
      order: 32,
      name: '7-10节',
      sections: ['第7节', '第8节', '第9节', '第10节'],
      startTime: '16:30',
      endTime: '20:40',
    ),
    PeriodDefinition(
      order: 33,
      name: '7-9节',
      sections: ['第7节', '第8节', '第9节'],
      startTime: '16:30',
      endTime: '19:45',
    ),
    PeriodDefinition(
      order: 34,
      name: '第7节',
      sections: ['第7节'],
      startTime: '16:30',
      endTime: '17:15',
    ),
    PeriodDefinition(
      order: 35,
      name: '下午78节',
      sections: ['第7节', '第8节'],
      startTime: '16:30',
      endTime: '18:10',
    ),
    PeriodDefinition(
      order: 36,
      name: '7-11节',
      sections: ['第7节', '第8节', '第9节', '第10节', '第11节'],
      startTime: '16:30',
      endTime: '21:35',
    ),
    PeriodDefinition(
      order: 37,
      name: '7-12节',
      sections: ['第7节', '第8节', '第9节', '第10节', '第11节', '第12节'],
      startTime: '16:30',
      endTime: '22:30',
    ),
    PeriodDefinition(
      order: 38,
      name: '第8节',
      sections: ['第8节'],
      startTime: '17:25',
      endTime: '18:10',
    ),
    PeriodDefinition(
      order: 39,
      name: '8-10节',
      sections: ['第8节', '第9节', '第10节'],
      startTime: '17:25',
      endTime: '20:40',
    ),
    PeriodDefinition(
      order: 40,
      name: '晚9-12节',
      sections: ['第9节', '第10节', '第11节', '第12节'],
      startTime: '19:00',
      endTime: '22:30',
    ),
    PeriodDefinition(
      order: 41,
      name: '晚9-11节',
      sections: ['第9节', '第10节', '第11节'],
      startTime: '19:00',
      endTime: '21:35',
    ),
    PeriodDefinition(
      order: 42,
      name: '晚9-10节',
      sections: ['第9节', '第10节'],
      startTime: '19:00',
      endTime: '20:40',
    ),
    PeriodDefinition(
      order: 43,
      name: '第9节',
      sections: ['第9节'],
      startTime: '19:00',
      endTime: '19:45',
    ),
    PeriodDefinition(
      order: 44,
      name: '10-12节',
      sections: ['第10节', '第11节', '第12节'],
      startTime: '19:55',
      endTime: '22:30',
    ),
    PeriodDefinition(
      order: 45,
      name: '第10节',
      sections: ['第10节'],
      startTime: '19:55',
      endTime: '20:40',
    ),
    PeriodDefinition(
      order: 46,
      name: '晚11-12节',
      sections: ['第11节', '第12节'],
      startTime: '20:50',
      endTime: '22:30',
    ),
    PeriodDefinition(
      order: 47,
      name: '第11节',
      sections: ['第11节'],
      startTime: '20:50',
      endTime: '21:35',
    ),
    PeriodDefinition(
      order: 48,
      name: '第12节',
      sections: ['第12节'],
      startTime: '21:45',
      endTime: '22:30',
    ),
  ];
}
